CREATE DATABASE Torneo_Ajedrez;

USE Torneo_Ajedrez;

CREATE TABLE Torneo(
id_Torneo INT AUTO_INCREMENT PRIMARY KEY,
Nombre_Torneo VARCHAR(15) NOT NULL,
Fecha_INICIO DATETIME NOT NULL,
Fecha_FIN DATETIME NOT NULL); 

CREATE TABLE Recinto(
id_Recinto INT AUTO_INCREMENT PRIMARY KEY,
id_Torneo INT NOT NULL,
Nombre_Recinto VARCHAR(30) NOT NULL,
Nombre_Ciudad VARCHAR(20),
Direccion VARCHAR(40) NOT NULL,

CONSTRAINT FK_RECINTO_TORNEO
FOREIGN KEY (id_Torneo) REFERENCES Torneo (id_Torneo)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE Patrocinadores(
id_Patrocinador INT AUTO_INCREMENT PRIMARY KEY,
Nombre_Patrocinador VARCHAR(20) NOT NULL,
Nº_Contacto varchar(14) NOT NULL,
Mail VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE Se_Patrocina(
id_Torneo INT NOT NULL,
id_Patrocinador INT NOT NULL,
PRIMARY KEY(id_Torneo, id_Patrocinador),

CONSTRAINT FK_PATROCINA_TORNEO
FOREIGN KEY (id_Torneo) REFERENCES Torneo (id_Torneo)
ON UPDATE CASCADE
ON DELETE RESTRICT,

CONSTRAINT FK_PATROCINA_PATROCINADOR
FOREIGN KEY (id_Patrocinador) REFERENCES Patrocinadores (id_Patrocinador)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE Formato_Torneo(
id_Tipo_Torneo INT AUTO_INCREMENT PRIMARY KEY,
id_Torneo INT NOT NULL,
Categoria VARCHAR(30) NOT NULL,
Reglas VARCHAR(100) NOT NULL,

CONSTRAINT FK_FORMATO_TORNEO_TORNEO
FOREIGN KEY (id_Torneo) REFERENCES Torneo (id_Torneo)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE Club(
id_Club INT AUTO_INCREMENT PRIMARY KEY,
id_Tipo_Torneo INT NOT NULL,
Nombre_Club VARCHAR(20) UNIQUE NOT NULL,
MAIL varchar(50) UNIQUE NOT NULL,
Nombre_Representante VARCHAR(40) UNIQUE NOT NULL,
Telf_Representante VARCHAR(14) NOT NULL UNIQUE,

CONSTRAINT FK_CLUB_TIPO_TORNEO
FOREIGN KEY (id_Tipo_Torneo) REFERENCES Formato_Torneo (id_Tipo_Torneo)
ON UPDATE CASCADE
ON DELETE RESTRICT 
);

CREATE TABLE Jugadores(
id_Jugador INT AUTO_INCREMENT PRIMARY KEY,
id_Tipo_Torneo INT NOT NULL,
id_Club INT,
Nombre_Jugador VARCHAR(40) NOT NULL,
DNI VARCHAR(10) UNIQUE NOT NULL,
MAIL VARCHAR(50) UNIQUE NOT NULL,
Telefono VARCHAR(14),

CONSTRAINT FK_JUGADORES_TIPO_TORNEO
FOREIGN KEY (id_Tipo_Torneo) REFERENCES Formato_Torneo (id_Tipo_Torneo)
ON UPDATE CASCADE
ON DELETE RESTRICT,

CONSTRAINT FK_JUGADORES_CLUB
FOREIGN KEY (id_Club) REFERENCES CLUB (id_Club)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE Clasificacion(
id_Clasificacion INT AUTO_INCREMENT PRIMARY KEY,
id_Tipo_Torneo INT NOT NULL,
id_Jugador INT,
id_Club INT,
Puntuacion INT,
Clasificacotira VARCHAR(20),

CONSTRAINT FK_CLASIFICACION_TIPO_TORNEO
FOREIGN KEY (id_Tipo_Torneo) REFERENCES Formato_Torneo (id_Tipo_Torneo)
ON UPDATE CASCADE
ON DELETE RESTRICT,

CONSTRAINT FK_CLASIFICACION_Jugador
FOREIGN KEY (id_Jugador) REFERENCES Jugadores (id_Jugador)
ON UPDATE CASCADE
ON DELETE RESTRICT,

CONSTRAINT FK_CLASIFICACION_CLUB
FOREIGN KEY (id_Club) REFERENCES Club (id_Club)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE Staff(
id_Staff INT AUTO_INCREMENT PRIMARY KEY,
id_Torneo INT NOT NULL,
Nombre_Staff VARCHAR(15) NOT NULL,
Apellido_staff VARCHAR(30) NOT NULL,
DNI_Staff VARCHAR(10) UNIQUE NOT NULL,
Telefono_Staff VARCHAR(14) UNIQUE NOT NULL,
Rol VARCHAR(15) NOT NULL,
Salario DOUBLE NOT NULL,
Nº_Cuenta LONG NOT NULL,

CONSTRAINT FK_STAFF_TIPO_TORNEO
FOREIGN KEY (id_Torneo) REFERENCES Formato_Torneo (id_Torneo)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE Partidas(
id_Partida INT AUTO_INCREMENT PRIMARY KEY,
id_Staff INT NOT NULL,
id_Tipo_Torneo INT NOT NULL,
MESA INT NOT NULL,

CONSTRAINT FK_PARTIDAS_STAFF
FOREIGN KEY (id_Staff) REFERENCES Staff (id_Staff)
ON UPDATE CASCADE
ON DELETE RESTRICT,

CONSTRAINT FK_PARTIDAS_TIPO_TORNEO
FOREIGN KEY (id_Tipo_Torneo) REFERENCES Formato_Torneo (id_Tipo_Torneo)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE Juegan(
id_Jugador INT NOT NULL,
id_Partida INT NOT NULL,
PRIMARY KEY (id_Jugador, id_Partida),

CONSTRAINT FK_JUEGAN_JUGADOR
FOREIGN KEY (id_Jugador) REFERENCES Jugadores (id_Jugador)
ON UPDATE CASCADE
ON DELETE RESTRICT,

CONSTRAINT FK_JUEGAN_PARTIDA
FOREIGN KEY (id_Partida) REFERENCES Partidas (id_Partida)
ON UPDATE CASCADE
ON DELETE RESTRICT
);

CREATE TABLE Movimientos(
id_Movimiento INT AUTO_INCREMENT PRIMARY KEY,
id_Partida INT NOT NULL,
Blancas VARCHAR(7) NOT NULL,
Negras VARCHAR(6),

CONSTRAINT FK_Movimientos_PARTIDA
FOREIGN KEY (id_Partida) REFERENCES Partidas (id_Partida)
ON UPDATE CASCADE
ON DELETE RESTRICT
);